### ISSUE TITLE
Errors in installing the server software with nmp (node-gyp rebuild fails)

### ISSUE THREAD

**Issue by npdoty** [tapchat/tapchat#1]
On two different server environments I've run into variations of this problem, that `node-gyp rebuild` fails during the sqlite3 install script. Here's the full error on my Mac laptop:

```
make: *** [Release/obj.target/sqlite3/deps/sqlite3/sqlite3.o] Error 1
gyp ERR! rebuild error Error: `make` failed with exit code: 2
gyp ERR! rebuild error     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:214:23)
gyp ERR! rebuild error     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! rebuild error     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! not ok 
npm ERR! sqlite3@2.1.5 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the sqlite3@2.1.5 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
```

This is preceded by hundreds of lines of warnings/errors regarding `../deps/sqlite3/sqlite3.c` and `../src/daemon.cc:226`. Fuller logs available on request.

**Comment by codebutler** [comment]
Hi, are you still unable to install TapChat? What version of node/npm/osx are you using?

**Comment by npdoty** [comment]
I still run into this error message with node 0.8.14 (installed today, via package installer), npm 1.1.65 (installed as part of that same package), on OS X 10.8. I don't have apt-get on this particular machine, so I haven't installed the prerequisites through the now recommended apt-get commands, though I thought npm would manage those dependencies.

(Thanks for following up!)

**Comment by zhongfu** [comment]
It could be node-gyp being missing, try `sudo npm install -g node-gyp`.

**Comment by codebutler** [comment]
Closing this issue, please open a new one if you're still having problems.

**Comment by npdoty** [comment]
While `npm install` still fails for me on the same error, if I clone the repo (which now uses a more recent version of the sqlite3 package in its dependencies) I can build successfully.

Can you update the package on `npm` to use the new `package.json`?

**Comment by codebutler** [comment]
Published!
