### ISSUE TITLE
Tapchat Installation:Failure in SSL library

### ISSUE THREAD

**Issue by julianwp** [tapchat/tapchat#20]
i use tapchat on vps with ip
31.220.63.47:2212 running on Ubuntu
10.04
i already have follow the instruction
of installing dependencies and
also the tapchat app
Shell Command History
apt-get update
apt-get install openssl
apt-get install python-software-
properties
add-apt-repository ppa:chris-lea/
node.js
apt-get update
apt-get install nodejs npm
libsqlite3-dev build-essential
npm install tapchat -g
tapchat start
port using 2212
password using my root password
when i open the android app what i
do is
1. choose Use Tapchat Server
2. Insert the server :
31.220.63.47:2212
3. password using my tapchat/root
password
but when i tap connect, it said
javax.net.ssl.SSLProtocolException:SSL
handsake aborted
ssl=0x1e8a38: Failure in SSL library,
usually a protocol error
error 140770FC:SSL routines
SSL23_GET_SERVER_HELLO: unknown
protocol
(external/openssl/ssl/
s23_clnt.c:683 .....)
what does it mean?
and what i supposed to do?
thanks a lot for any responses :)

**Comment by codebutler** [comment]
Are you still having this error?
