### ISSUE TITLE
Notifications not working.

### ISSUE THREAD

**Issue by sangh** [tapchat/tapchat#65]
So I noticed a while ago that notifications just stopped working (the debug log just says error 500 with is pretty unhelpful) and going directly to `https://tapchat.herokuapp.com/notify/` seems like it is not working anymore.  So, did that go down, or are you changing it so people have to host their own notification endpoint?

BTW, apart from the bugs, I love this thing.

**Comment by sangh** [comment]
Hum, so the deafening silence might mean that I'm the only one.

**Comment by tomee** [comment]
Not working for me either (tapchat hosted on my own server)...

**Comment by sangh** [comment]
Yeah, mine is my own server as well.  Good to know I'm not the only one.

**Comment by lharding** [comment]
Not working for me either, and `https://tapchat.herokuapp.com/notify` is now just a 404 page.

**Comment by sangh** [comment]
Are you hosting yourself?  (I'm asking b/c the rest of the commenters are, so it may just be that the hosted one doesn't get a 404.  Really I'm just stabbing in the dark.)

**Comment by matthewpucc** [comment]
not working on a self hosted server for me either

**Comment by Wallbraker** [comment]
Not working for me as well on a self hosted server.

**Comment by sangh** [comment]
OK, then, so short of an answer from @codebutler, I think it is likely that this just no longer works from self-hosted servers (but may still from IRC cloud or whatever).  I guess then the only thing is to have people hand-hack something together that will work for them (like using Pushbullet (and their API) to send yourself a push request).  The code that needs changing is in tapchat/push_client.

**Comment by cwallace** [comment]
I love Tapchat, but push notifications is really what separated it from other IRC clients. It would be great if @codebutler would update so that we can self-host the notification portion or utilize one of the many free notification services. He's been active as recently as last week on another project, so I'm not certain if he's just done with Tapchat or just busy with other projects. I'm hoping it's the latter and this can get resolved.

**Comment by matthewpucc** [comment]
Im currently working on a solution for this. If anyone has a particular push service they want me to launch with, let me know.

**Comment by codebutler** [comment]
Hi everyone, please force-stop TapChat on your device and re-launch it. Push notifications should be working again.

**Comment by tomee** [comment]
Not working for me (self-hosted server). I'm using version 3.0.0 (that's what Android App Manager says). When the app is in foreground, a query nickname is shown in bold on new activity, but when the app is in background, no notification is shown. Plus, it seems to reconnect to the server each time it is brought to foreground.

**Comment by sangh** [comment]
They do work (again) for me after this change (on a self-hosted server).  Thanks @codebutler !

**Comment by sangh** [comment]
@tomee the connecting and highlighting (when connected) are how Tapchat has always worked, and neither one of those are really related to the push notifications.

I'm going to close, but feel free to open another issue if you they still don't work after updating the server and force-stopping the client.

**Comment by tomee** [comment]
As for TapChat re-establishing the main connection, that's what I thought, but wasn't sure since the notifications never worked for me (been using the app for only a short period). Could you perhaps post a screenshot of how the notification should look like?
I see no changes to the git repository so I assume the fix was on the push-server side. I've reinstalled tapchat on my server and re-created the settings folder but it didn't help...

**Comment by sangh** [comment]
It looks like a push notification, that is, it is on the main phone's drop-down where missed calls and wi-fi networks show up.  Did you _force_ stop the tapchat app on your phone?  Do that, and then go to a channel you are in and type "${nick}: ${some message}", then wait some.  If that doesn't work, then I'm not sure what else you can try.  Do you get push notifications _at_all_? (As in for any app?)

And yes, the fix was on the server side.

**Comment by tomee** [comment]
Yes, I did force-stop the app. And I do have notifications from other apps. It's still not working here... but I think the self-hosted part might be a problem, the notification traffic should go to tapchat.herokuapp.com, right?

**Comment by sangh** [comment]
Yeah.  Mine is self-hosted as well and since Eric's update it works fine.  I guess you should instrument push_client.js to see what error the call is returning.
