### ISSUE TITLE
RSA_padding_check_PKCS1_type_1:block type is not 01

### ISSUE THREAD

**Issue by vibragiel** [tapchat/tapchat#7]
I'm using my own tapchat server without issues with clients on a Samsung Galaxy S3 and a Nexus 7. However, when I tried to install the client on my Nexus One (Android 2.3.4), I got the message above during the SSL handshake, when trying to log into the tapchat server.

**Comment by codebutler** [comment]
Closing this issue, please open a new one if you're still having problems.
